spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.244.172.241:3306/medical_work?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com/sun/praticaltrainingwork/domain/DO
  mapper-locations: classpath*:/mapper/**/*.xml
  jwt:
    secret: "your-256-bit-secret-key-must-be-at-least-32-chars" # 必须≥32个字符
    expire: 604800000 # 7天(毫秒)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html